# from name: plasmabio-template-r

name: Plasma-demo
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - jupyterlab=3
  - nbresuse
  - nodejs
  - libgomp
  - r-irkernel
  - r-base>=4
  - r-tidyverse 
  - r-Matrix
  - r-lattice
  - r-rpart
  - r-RSQLite
  - r-gplots
  - r-ggplot2
  
